version: "2"
services:
  node:
    image: "node:10"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
     - ../../:/home/node/app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    command: "sh ./scripts/entrypoints/${NPM_SCRIPT}.sh"
